- bumps/cli.py
On UNIX platforms time.clock() gives the processor time used on a particular thread. Time.time() is a more platform-independent way of using the actual wall time.
> fixed --time switch to be more robust across platforms

- bumps/gui/app_panel.py
wx.OPEN -> wx.FD_OPEN, wx.SAVE -> wx.FD_SAVE... etc.
> use more standard names compatible with wx Phoenix 

- bumps/wsolve.py
On x86 hardware (Python 2.7.14 on Debian's i386 port) the test against a known problem fails due to numerical precision. The attached patch uses `numpy`'s `assert_almost_equal` to test more robustly; one could reinvent an `assert abs(a - b) / a < delta` instead but since `numpy` is already used throughout, there's no harm in using it here too.
```Check that results are correct for a known problem. ... > /build/python-bumps-FiUVML/python-bumps-0.7.6/.pybuild/pythonX.Y_2.7/build/bumps/wsolve.py(447)test()
-> assert py == poly(px), "direct call to poly function fails"
(Pdb) py
array([ 13.18486645])
(Pdb) px
array([ 1.5])
(Pdb) poly(px)
array([ 13.18486645])
(Pdb) py - poly(px)
array([  1.77635684e-15])
```
> Allow for numerical precision in test

- bumps/gui/data_view.py
- bumps/gui/util.py
The wx backend no longer exposes both NavigationToolbar2WxAgg and NavigationToolbar2Wx, generating an ImportError from gui/data_view.py
> Fix imports for matplotlib 2.2.2

- .travis.yml
- bumps/numdifftools/core.py
- bumps/numdifftools/info.py
numpy 1.14 changes the output format for printing and would break the doctests throughout; tell numpy to use the 1.13 format instead.
(This PR is built on top of the travis-ci one so that it is tested; I can rebase if needed so that it's only the single commit.)
> Use numpy legacy output format when doing doctests

- bumps/parameter.py
I added a `to_dict()` to `BaseParameter` so that `refl1d` can serialize some of its objects.
Note: I went with the `to_dict` name mostly because it can then be used for other purposes than just producing json files. Adding extra info such as class name seemed to make dictionaries reasonable.
> Add to_dict() for serialization

- .github/workflows/test.yml
- doc/conf.py
The bumps `doc/Makefile` sets `-n` in `SPHINXOPTS` but CI does not test it with that. SasView CI uses the Makefile and so fails when sphinx finds nitpicks that have never been tested in CI.
This PR
* enables `-n` in the CI
* fixes some nitpicks that sphinx is currently complaining about.
(Hopefully this is enough to get SasView CI passing again)
> Make sphinx nitpick-happy

- bumps/wsolve.py
Running tests gave the following warning 
```
bumps/wsolve.py::bumps.wsolve
<doctest bumps.wsolve[2]>:1: PendingDeprecationWarning: the matrix subclass is not the recommended way to represent matrices or deal with linear algebra (see https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html). Please adjust your code to use regular ndarray.
```
This was from some documentation code, that gave an example using the [now deprecated](https://stackoverflow.com/questions/53254738/deprecation-status-of-the-numpy-matrix-class) matrix class instead of `np.array`. 
I have made a like for like change to the doc string.
> Use to array instead of matrix

- .github/workflows/test.yml
- bumps/curve.py
- bumps/fitproblem.py
- bumps/util.py
Apply some updates, replacing deprecated inspect.getargspec with inspect.signature and apply a __name__ attribute to the DynamicPackage created when the model is loaded.  These two fixes together enable @numba.jit functions in a user model.
Addresses #65
> Allow numba models

- bumps/gui/summary_view.py
After upgrading to Ubuntu 20.04, the sliders on the summary view no longer appear.  I didn't find a smoking gun as to why this was happening, but after removing the fixed pixel-height for the slider on add to the sizer (using -1 instead) the sliders reappeared.  The default height for the sliders is pretty tall, which is why the fixed height was probably added in the first place.  To compensate and get back to roughly the same vertical density a negative vertical margin was specified for the GridBagSizer, with some additional margins added to the header to compensate for that.
I verified that the result displays properly in OSX and Windows 10
> Summary view fix

- bumps/gui/summary_view.py
Floating-point values in summary view were overflowing the columns for "value".  This applies a uniform %.10g string format to all the values in the view.
> apply string formatting (%.10g) to values in summary view

- bumps/dream/compiled.c
In packaging bumps 0.9.0, we noticed that the dream/bounds.py tests were failing; the failures were not always identical but were always when the bounds were reflected or folded on the multidimensional test at `bounds.py:207`, with 1 or 2 of the vectors not having the bounds applied to them correctly, and so the `norm` not evaluating to `0`.
After much gnashing of teeth, we found that the failures often went away when running within the debugger,  could be suppressed entirely if the C bounds code was not used (by setting `dll=None` in the python module), and could also be suppressed by preventing OpenMP from doing any parallelisation (by setting `OMP_NUM_THREADS=1` in the environment.
Looking at the C functions `bounds_reflect`, `bounds_clip`, `bounds_fold`, they each contain nested loops …
> Mark inner loop variables as private for openmp in bounds calculations

- .github/workflows/test.yml
CI is currently failing because:
- Python 3.6 is no longer available in the `ubuntu-latest` image and so CI fail there.
- bumps is not compatible with scipy 1.10
- bumps is not compatible with numpy 1.24
It's also very much time to add some newer Python 3 releases to the CI matrix.
This PR doesn't fix CI, it's only addressing the first point of the 3 failures. I'll put the other 2 into a new issue.
> Drop unsupported Python 3.6, add supported 3.10, 3.11

- .github/workflows/test.yml
- bumps/dream/entropy.py
- bumps/mpfit.py
This PR addresses the (in)compatibility of bumps with scipy 1.10 and numpy 1.24.
* Include the updates required for scipy 1.10 as discussed in #118 (thanks to Drew Parsons for the patch via the Debian packaging for bumps)
* Update np.float and np.int to used defined sizes for numpy 1.24 compatibility
* cherry-pick commit to drop Python 3.6 from CI; this is necessary to get *any* CI to pass at present as there python 3.6 is not available in the CI matrix any more. (Cherry-picked from #117; as noted there, CI for master currently fails and merging this commit is a prereq to get anything useful out of CI)
Closes: #118
> Update code and tests for scipy 1.10 and numpy 1.24

- bumps/dream/corrplot.py
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [corrplot.py](https://github.com/bumps/bumps/tree/master/bumps/dream/corrplot.py#L44), class: Corr2d, there is a special method [`__getitem__`](https://docs.python.org/3/reference/datamodel.html#object.__getitem__) that contains an unexpected number of parameters. Each call to this method will result in a TypeError. iCR suggested that special methods should have an expected number of parameters. More infomation can be found in the Python [documentation on the various special method](https://docs.python.org/3/reference/datamodel.html#special-method-names).
Since the implementation of method `__getitem__` requires the use of two indices (i, j), I've converted the parameter to a tuple. In this …
> Fixed Improper Method Call: `__getitem__`

- bumps/gui/uncertainty_view.py
Allows you to set the number of correlations to show using `CorrelationView.MAX_CORR`, or `CorrelationView().MAX_CORR`.
If the number of correlations is exceeded it clears the figure and plots nothing.
> Clear correlation_plot if nvars > MAX_CORR. Fixes #134

- bumps/dream/formatnum.py
- bumps/dream/walk.py
- bumps/fitproblem.py
- bumps/formatnum.py
- bumps/pytwalk.py
- bumps/simplex.py
There are some breaking changes in numpy version 2.0, which is now the version installed by default with 
```
pip install numpy
```
This PR attempts to address them all:
- numpy.NaN -> numpy.nan
- numpy.mat -> numpy.asmatrix
- numpy.asfarray -> numpy.asarray(..., dtype=float)
> Numpy 2.0 compat

- bumps/mpfit.py
**Bug**
In `bumps/mpfit.py`, line 1223:
```
...
catch_msg = 'calling '+str(fcn)
[self.status, wa4] = self.call(fcn, self.params, functkw)
if (self.status < 0):
self.errmsg = 'WARNING: premature termination by "'+fcn+'"'
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
TypeError: can only concatenate str (not "method") to str
```
**Fix**
Convert `fcn` to string:
```
...
self.errmsg = 'WARNING: premature termination by "'+str(fcn)+'"'
...
```
**Testing**
Seems to be a very simple syntax error that was probably never encountered due to being a warning message for an edge case. The corrected version seems to run as intended.
> Fix bug preventing warning message from displaying correctly

- bumps/fitters.py
- pyproject.toml
Use automated package discovery with setuptools to make sure to get all parts of the mystic package in bumps.
Also adds a test in `bumps/fitters.py` that checks that all the active fitters can be run on a simple problem, producing acceptable fit results and errors (dream errors are too variable and are not checked)
> Fix mystic import

- bumps/webview/client/src/components/CSVTable.vue
- bumps/webview/client/src/components/CustomPlot.vue
- bumps/webview/client/src/components/CustomUncertaintyPlot.vue
- bumps/webview/server/api.py
- bumps/webview/server/custom_plot.py
Adds webview support for static tabular data provided as CSV.
Currently only used as a custom plot option, but could also be used to create standard tabs containing tabular data (most immediately a parameter statistics tab showing 68% and 95% CIs on the fit parameters).
This implementation is extremely lightweight and extensible:
1. The base python CSV parser is used to generate header and row data
2. I made a new Vue component to render the table from the parsed data and allow the user to download the raw data (note that the raw data are included along with the parsed data to avoid an extraneous server call; I imagine we'll mostly be dealing with small tables so the duplication makes sense).
Screenshot (formatting / contents controlled by source, not the webview renderer):
> Custom plot table

- bumps/webview/client/src/components/ParameterTraceView.vue
- bumps/webview/server/api.py
- bumps/webview/server/colors.py
- bumps/webview/server/traceplot.py
Fresh version of https://github.com/bumps/bumps/pull/168
Update to the parameter trace plot. Major changes:
1. Plot is now rendered in plotly
2. Any fittable parameter can be selected for inspection.
3. Colors has been moved from refl1d to bumps
An open question:
At the moment the parameter trace plot is using uncertainty_state, and it updates with the "updated_uncertainty" signal. It is not clear to me if the information in this plot can be updated more regularly; a more natural update signal would be "updated_convergence", but of course at the moment the uncertainty state isn't updated with the convergence updates so this doesn't really make sense.
> Trace plot update

- bumps/webview/server/api.py
- bumps/webview/server/fit_thread.py
The fit_complete handler in the webview API is intended to be the last thing that runs at the end of a fit.
The signals and locks were not enforcing this.  This PR moves `fit_uncertainty_final.wait` to run before the start of execution of the fit_complete handler.
Related, it also causes the DREAM monitor to always emit the `uncertainty_final` progress event, even if no uncertainty is defined (if `uncertainty_state == None`).
> Webview: Ensure fit complete handler runs after uncertainty_final event handled

- bumps/webview/server/webserver.py
- extra/platform_scripts/bumps_webview.app/bumps_webview
- extra/platform_scripts/bumps_webview.bat
- extra/platform_scripts/make_linux_desktop_shortcut.sh
Add startup flag to make usage of the persistent path optional.
The primary use case of the persistent path will probably be people starting the application from a shortcut, so that they can quickly navigate to the same folder they were previously using.
For users on the command line, it would be more convenient to use the current working directory, so the flag is False by default, but enabled in all the shortcuts that are deployed.
> Optional persistent path

- bumps/webview/server/api.py
An unrecoverable GUI state was occurring when users moved or deleted a folder that was the "most recent folder" persisted to disk (base_path), then tried to open a model from the file browser.
The server was trying to fall back to the `base_path`, but that was the path that was missing, so the file browser never opened (it received an error message every time).
This PR removes the error message reply, which is not useful at this time, and instead falls back to the current working directory if the specified directory does not exist.
> fall back to current working directory if state.base_path does not exist

- bumps/webview/client/src/components/SummaryView.vue
In the Summary tab of the webview gui, show how many fit parameters are being shown in parentheses in the header of the column (showing the number of filtered parameters actually being shown).
Fixes #166
> add count of displayed parameters to 'Fit Parameter' heading

- bumps/bounds.py
Currently, attempting to use the `bumps.bounds.Normal` distribution results in an exception during initialization of the class, because the initialization of the ancestor `Distribution` class does `self.dist = dist`, which is forbidden on a frozen dataclass.
Instead, we can use `__post_init__` with `object.__setattr__` during initialization to write to private attributes
> Fix bug where you can't initialize (frozen) Normal distribution dataclass instance

- bumps/errplot.py
In errplot, the function `calculate_errors_from_state` does 2 distinct things:
- generates a list of points at which to calculate
- calls the `calc_errors` function on those points, with the fitProblem (which then calls `fitplugin.calc_errors` with the problem and points)
Here we separate this into two functions, one of which generates the list of points, and the other of which calls `calc_errors`.  In this way,  an application can directly use the point-generating function to implement a statistical error calculation, without using the fitplugin architecture.
> separate the generation of error points to calculate from the calculation call

- bumps/gui/convergence_view.py
- bumps/webview/server/fit_thread.py
This might not be the right way to handle this, but it seems that `history.population_values == [None]` so that `pop is None` the first time `ConvergenceMonitor.__call__` is invoked during an `lmfit` fit session.  This causes the expression `len(pop)` on line 92 of `bumps/webview/server/fit_thread.py` (and also in `bumps/gui/convergence_view.py`) to throw a TypeError exception.
One way to handle it is to catch the TypeError.  Another would be to alter the guard statement to check if `pop` would be `None`.
Probably worth looking over to make sure we're really fixing the error (it seems weird that for that fitter `history.population_values == [None]` on the first call, when that doesn't happen for other fitters)
> catch error returned on first run of lmfit (TypeError)

- bumps/dream/model.py
- bumps/dream/views.py
- bumps/fitproblem.py
- bumps/parameter.py
- bumps/pdfwrapper.py
- doc/examples/test_functions/mixture.py
The gaussian mixture example demonstrates that the dream fitter can return the correct posterior distribution.
It was broken in python 3 since zip returns an iterator that is being looped multiple times. The iterator is now turned into a tuple.
A slight tweak to the plotting for when there are bad values for log probability: clear these values before creating the histogram.
> Fix gaussian mixture example

- bumps/__init__.py
- bumps/plugin.py
- bumps/serialize.py
- bumps/util.py
- bumps/webview/server/state_hdf5_backed.py
This PR 
- adds a new `libraries` property to the serialized JSON format for models, which provides a `version` string and `schema` string for the libraries from which serialized dataclasses are made for a particular model.
- adds a new `migrate_serialized(serialized_obj: bytes)` method to the interface of `bumps.plugin`, to support application-specific model migration prior to deserialization.
During the serialization, a library of package metadata is created.  As the model tree is walked, as each dataclass encountered is inspected to see which python package corresponds to the module and class it represents.  If that package has not yet bet added to the metadata, the version is extracted from the package and the `__schema_version__` attribute is read from the base module of the class …
> Add application schema to serialized metadata, helps with application model migration

- bumps/webview/client/src/components/DataView.vue
The data view in bumps webview was broken - selecting models was not working (nor was multiple selection).
This PR fixes that issue (models that can't overplot on the same matplotlib figure still won't properly plot if multiple is selected)
> Fix model select in webview data panel

- bumps/webview/client/src/components/CorrelationViewPlotly.vue
- bumps/webview/client/src/components/ParameterTraceView.vue
- bumps/webview/client/src/components/UncertaintyView.vue
as happens when a new fit starts and the uncertainty state is empty, and the server returns "None" for all the plots
Current behavior is to throw a client error because processing the plotdata fails when plotdata is null.
> clear uncertainty plots if returned plottable is null 

- bumps/webview/build_client.py
- extra/build_conda_packed.sh
add --no-deps flag (by default, False) to bumps.webview.build_client
This change means that `npm install` is run by default when building the client with the python helper, rather than not being run by default.
If no `node_modules` folder is found, `npm install` is still run no matter what the --no-deps flag value is.
> Default install client dependencies

- pyproject.toml
- `scikit-learn` is used only in entropy.py, and is lazily imported in there.  It is not used in any of the main operations of the bumps library, so I don't think it should be listed as a dependency.
- `typing_extensions` isn't used at all.
> remove unused dependencies

- bumps/webview/client/src/App.vue
- bumps/webview/client/src/app_state.ts
- bumps/webview/client/src/components/ServerShutdown.vue
- bumps/webview/client/src/components/ServerStartup.vue
- bumps/webview/server/api.py
Currently, if the user quits the server (or it is terminated) any client window that is connected to that server shows a dialog with "Server shutting down" and a "DISMISS" button.
The button is supposed to prevent the tab/window from auto-closing, but this is not obvious to the user based on the dialog and button wording.  
Also, currently if the user clicks "DISMISS" the next thing they see is another dialog with "Server connecting..." and a spinner that spins endlessly, but even if another server is started at the same hostname/port, the client never reconnects.
This PR fixes the second issue (the client does attempt to reconnect), and also shows a more informative dialog when the server shuts down.
The PR removes the "Connected" and "Disconnected" indicators in the upper-right of the …
> Disconnected dialog refactor

- bumps/webview/client/src/components/HistoryView.vue
- bumps/webview/server/api.py
- bumps/webview/server/state_hdf5_backed.py
This PR does 2 things 
1. Uses a dict for storing `HistoryItem` items in the session history, instead of a list
2. Uses a unique name derived from the timestamp instead of the raw timestamp as the key of that dict
This is to avoid a name conflict if more than one history item is appended within the resolution of the timestamp we are using (milliseconds)
> Ensure unique names for session history items

- bumps/webview/client/src/app_state.ts
- bumps/webview/server/api.py
- bumps/webview/server/cli.py
- bumps/webview/server/fit_options.py
- bumps/webview/server/state_hdf5_backed.py
- bumps/webview/server/webserver.py
Populates the shared state in webview (`api.state.shared`) with all the default fit options, updated with any overrides specified on the command line e.g. when doing 
```sh
bumps model.py --fit=dream --steps=1234
```
... the number of steps shown in the fit options dialog in the webview gui will indeed be 1234.
> synchronize CLI fit options with the webview interface

- bumps/bounds.py
- bumps/cli.py
- bumps/dream/core.py
- bumps/fitters.py
- bumps/gui/fit_thread.py
- bumps/mystic/solver.py
- bumps/options.py
- bumps/parameter.py
- bumps/partemp.py
- bumps/quasinewton.py
- bumps/random_lines.py
- bumps/util.py
- bumps/webview/client/src/components/FitOptions.vue
- bumps/webview/server/api.py
- bumps/webview/server/cli.py
- bumps/webview/server/fit_options.py
- bumps/webview/server/fit_thread.py
- check_fitters.py
- doc/conf.py
- doc/sitedoc.py
Refactor the interaction between the fitters and controller.
MonitorRunner now includes info() for updates to the user during the fit and final() for updates at the end of the fit which are forwarded to each monitor.
MonitorRunner now includes stopping() so that the fitter can ask if the abort flag has been set. This replaces the abort_test parameter passed to each fitter. [It doesn't save much code, but it makes clear that MonitorRunner is handling bidirectional communication between the controller and the fitter.]
The fitters were all adapted to accept this interface. The internals of several fitters were already set up to look at the output of the monitor update to determine if the user requested stop. For these fitters, the redundant abort_test parameter was removed. [The abort_test …
> Show final step on console and rename near_best to jump

- bumps/webview/client/src/components/FitOptions.vue
- bumps/webview/server/api.py
- bumps/webview/server/fit_options.py
Currently the fitter fields (like steps, xtol, etc.) are defined on the server in `bumps.webview.server.fit_options`, and a matching definitions is maintained in TypeScript on the client in `bumps/webview/client/src/components/FitOptions.vue`
This PR
- adds a method that converts the FIT_OPTIONS from the server into a JSON-compatible form
- adds a method to the webview api for retrieving those fields
- refactors the FitOptions panel in the client to use these values
- (including adding new tooltips to the labels, with the extended description!)
- removes the deprecate TS definition of FIT_FIELDS in the client code
> Client fit fields from server

- bumps/fitters.py
- bumps/webview/server/api.py
- bumps/webview/server/state_hdf5_backed.py
Move max fit timeout handling to fit driver. This allows the time option to work in the simplified fit interface, and it simplifies the code.
> Allow time option in simple fitter

- bumps/dream/state.py
When loading a dream state from hdf5, coerce integer attrs to int (supports old serialization)
the following attributes are meant to be integers:
- good_chains
- gen_draws
- update_draws
but in the old serialization sometimes they are written as floats.  This PR coerces them with `astype(int)` to support existing session files
> Coerce dream integer attributes on load

- bumps/fitproblem.py
- bumps/fitters.py
There is an inconsistency in the output of MPfit, sometimes returning χ² and sometimes returning √χ².
Instead use nllf() on the result so that it is always consistent.
> Use nllf() rather than sum-squared residuals for lm return value

- bumps/webview/server/webserver.py
New versions of the client are not picked up when users upgrade bumps, as the index page is often cached (by Chrome, for instance).  Within that page, there is a unique (hashed) .js library and .css files, so we only need to worry about caching of the index page.  If a fresh version of the index html is loaded, then the correct .js and .css files will be loaded too.
send headers to prevent browsers from caching initial page, so that version changes to the client are naturally picked up
**Note** the index page is tiny, about 500 bytes, so not caching it is not a big deal.
> Prevent caching webview index page

- bumps/webview/server/cli.py
- bumps/webview/server/state_hdf5_backed.py
This PR adds a `version` kw argument to `cli.plugin_main`, which will be returned when the `--version` flag is used with the cli.
> Allow an app using bumps cli to specify a version

- bumps/fitproblem.py
Many end-users of the FitProblem class need access to the fitted parameters and are using the "private" `FitProblem._parameters` attribute to get them.
We already have a `FitProblem.labels()` method that provides a list of the labels for these in the order they are stored, and this PR adds a property `FitProblem.parameters` that returns the parameters from which those labels are derived.
> create public property to access FitProblem._parameters

- bumps/dream/convergence.py
- bumps/dream/core.py
- bumps/dream/state.py
- bumps/fitters.py
- bumps/webview/server/api.py
- bumps/webview/server/fit_thread.py
- bumps/webview/server/state_hdf5_backed.py
- bumps/webview/server/webserver.py
See #260
Fixes convergence test for --alpha in dream (the test was reversed).
Improves error reporting for webserver RPC calls.
Preserves total number of generations.
Note: DE reports wrong number of steps on resume, but that will be posted as a separate ticket.
> improve dream resume support

- bumps/parameter.py
Example usage, in a class where `thickness` is a calculated value:
```python
@dataclass(init=False)
class Stack(Layer):
"""
Reflectometry layer stack
A reflectometry sample is defined by a stack of layers. Each layer
has an interface describing how the top of the layer interacts with
the bottom of the overlaying layer. The stack may contain
"""
name: str
interface: Literal[None]
layers: List[Union["Slab", "Repeat"]]
thickness: Parameter = field(metadata={"description": "always equals the sum of the layer thicknesses"})
def __init__(
self,
layers: Optional[Union["Stack", List[Union["Slab", "Repeat"]]]] = None,
name: str = "Stack",
interface=None,
thickness: Optional[Parameter] = None,
):
self.name = name
self.interface = None
self._layers = []
self.thickness = …
```
> add a helper function to simplify usage of Calculation in models

- bumps/dream/convergence.py
- bumps/dream/core.py
- bumps/dream/state.py
- bumps/dream/views.py
- bumps/errplot.py
- bumps/fitters.py
- bumps/webview/server/api.py
Instead of generating an ephemeral private `._trimmed` attribute on the fitter class when the `trim` option is enabled, store the calculated portion in a new attribute `portion` on the Dream state.
Then this `portion` is used by default in the various dream plots and other outputs.
It is a public attribute of the Dream state because the user may wish to set it manually as well, e.g. in a GUI. 
The stored portion is also used by default in any `state.draw()` unless a float (non-None) `portion` kwarg is supplied e.g. `state.draw(portion=0.5...)`
> Store user-controlled 'portion' setting in Dream state

- bumps/webview/server/__init__.py
- bumps/webview/server/api.py
- bumps/webview/server/names.py
- bumps/webview/server/webserver.py
This PR adds a method with the same name as the new one provided in refl1d PR 299 for starting a webview server within a jupyter notebook: `start_jupyter_server`
This method automatically enables the webview link display on server start (the option `jupyter_link=True` is passed to `start_app`), and it returns an asyncio task that should be awaited in the notebook, in order to capture any exceptions that are raised during the server start, e.g.
```python
from bumps.webview.server.webserver import start_jupyter_server
await start_jupyter_server()
```
> Fix method for starting webview server in jupyter

- .github/workflows/test-publish.yml
- README.rst
- doc/getting_started/install.rst
- extra/build_conda_packed.sh
- pyproject.toml
Move all the dependencies from an extra "webview" group to the main dependencies in `pyproject.toml`
> Install webview dependencies by default

- bumps/webview/client/src/components/SummaryView.vue
- bumps/webview/server/api.py
Fixes:
- when a user toggles a previously fixed parameter to "fit", now shows correct limits (even if infinite)
- disables slider for parameter when any limit is infinite
- reverts value in editable box (value, min or max) to previous value if user inputs something that is not a number
- reverts value to previous if user presses `esc` while editing
- selects contents of editable box for easy replacement on focus (click on box or tab to box, start typing replacement text)
> Fix summary panel issues

- bumps/webview/client/src/App.vue
- bumps/webview/client/src/components/ServerShutdown.vue
pass disconnected state to Shutdown dialog as prop instead of trying to react to ref (which wasn't working)
> Fix shutdown dialog

- bumps/webview/server/cli.py
- check_fitters.py
- doc/examples/curvefit/curve.py
- doc/examples/entropy/check_entropy.py
- doc/examples/entropy/peak.py
- doc/examples/peaks/readme.rst
- doc/getting_started/install.rst
- doc/guide/fitting.rst
- doc/guide/options.rst
- extra/mc.py
The old program stored the results in a directory using --store. In the new program this is done with --export, while --store was used to specify the path to an hdf5 session file.
This PR drops --store/--read-store/--write-store from the command line, renaming them to --session/--read-session/--write-session.
We could keep --store as an alias for --export, though that will potentially confuse users who have been using --store=fit.h5 on the new version.
> Use --session rather than --store

- bumps/webview/client/src/components/ConvergenceView.vue
@acaruana2009 noticed that the burn line(s) on the convergence plot sometimes overlap the legend now.
This PR makes the legend draggable through plotly configuration, so the user can at least manually move things into a non-overlapping state.
It's possible we should also move the labels on the burn lines to be closer to the midpoint, so that this overlap is less likely overall?
> make legend draggable on convergence plot

- bumps/webview/client/package.json
- bumps/webview/client/tsconfig.json
use node-lts for tsconfig, stable version instead of pinning to particular node version
> use node-lts for tsconfig, stable version

- .gitignore
- bumps/webview/server/cli.py
Expand version CLI option with additional info about child app, bumps, python and system platform info. 
output now looks like: 
```
> refl1d --version
=======================================================
refl1d          1.0.0rc1.post3+g19112a35.d20250930
bumps           1.0.3+d20250930
Python          3.13.7
Platform        linux
=======================================================
```
Additionally print this same info to the console when starting webview.
> Expand --version, print when running webview

- bumps/webview/client/src/components/CorrelationViewPlotly.vue
- bumps/webview/client/src/components/UncertaintyView.vue
plotly types from DefinitelyTyped now cover registering heatmap, etc. ... shims not needed anymore
> Remove typing shims for registering plotly modules like Heatmap
